# This deployment describes the pods.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-gke-workload-identity
  namespace: gke-wi-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      serviceAccountName: gke-wi-ksa
      containers:
      - name: hello-app
        # TODO: Replace with your own image, or use the debricked example.
        image: cloudsteak/storage-explorer:latest
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            value: "8080"
        # TODO: replace with your own bucket name.
          - name: BUCKET_NAME
            value: cloudsteak-wi-bucket

